# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92927eca1e1972bd7492d1c4e4d3ff74781361815b57182d0567f29fa244e4b2646731e90357783e47c0dcb8b767827dfc552a95b7988ef3de76f34213fcdda8

test:
  secret_key_base: e1c6aa88e4b508b5369742d688f0c032854fef4af74987849edc8e0359d5290f974e78acba3e46603fc966b9cc2cad8526b187f6843bab481e725a08cd66ae35

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
